replacing_instructions_detailed = [
    "Write an descriptive depiction of the picture you see.",
    "Provide a detailed description of the given photo.",
    "Render a meticulous account of the various aspects of the image.",
    "Share an elaborate explanation of the picture before you.",
    "Produce a thorough rundown of the presented photograph.",
    "Offer an exhaustive description of the image.",
    "Examine the photo closely and relay its details.",
    "Explain the contents of the given photo with great attention to detail.",
    "Characterize the image in a highly detailed manner.",
    "Break down the components of the image in a comprehensive way.",
    "Elaborate the visual content of the image accureately and thoroughly.",
    "Portray every component depicted in the photograph.",
    "Illustrate the picture with a rich, illustrative narrative.",
    "Depict the picture using a detailed and vivid narrative.",
    "Compose an accurate and attentive report of the presented illustration.",
    "Deliver a thorough examination of the photo's components.",
    "Present an extensive analysis of the photograph's details.",
    "Describe the picture meticulously, leaving no detail out.",
    "Create an engaging narrative that accurately represents the image.",
]

replacing_instructions_brief = [
    "Describe the image in a nutshell.",
    "Give a brief summary of the given picture.",
    "Present a succinct overview of the photograph.",
    "Summarize the key visual elements of the image.",
    "Offer a short and clear description of the visual content in the image.",
    "Provide a concise explanation of what is shown in the photo.",
    "Share an abridged account of the scene depicted in the shown picture.",
    "Write a compact, clear interpretation of the picture.",
    "Relay a concise narrative representing the image presented.",
    "Render a condensed but informative portrayal of the picture.",
    "Communicate succinctly what's pictured in the provided photo.",
    "Make a compact description of the given illustration.",
    "Draft a concise rendering of the displayed image.",
    "Present a crisp and clear synopsis of the shown picture.",
]
